name: Run tests and validate pull requests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.labels[0].name != 'dependencies'
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi
          if [ -f requirements/test_requirements.txt ]; then pip install -r requirements/test_requirements.txt; fi
      - name: Test with pytest
        run: |
          ./run-tests.sh
